//! Database persistence layer.
//! Uses sqlx with runtime driver selection via `DATABASE_URL`:
//!   sqlite:~/.ilink-hub/ilink-hub.db → SQLite (default, file created if missing)
//!   postgres://user:pass@host/db      → PostgreSQL
//!   mysql://user:pass@host/db         → MySQL

use anyhow::Result;

use sqlx::AnyPool;

mod clients;

mod context;

mod credentials;

mod messages;

mod migrations;

mod sessions;

pub use clients::ClientRow;

pub use messages::{MessageRow, SessionStatusEntry};

pub use sessions::BackendSessionRow;

/// Backend driver. Parsed from the URL scheme prefix in `Store::connect`
/// (sqlite: / postgres: / mysql:). The migration runner needs this to
/// pick the right SQL dialect for `try_claim_migration`, the v5 `id` column
/// clause, and the `column_exists` pre-check — `ON CONFLICT ... RETURNING`,
/// `GENERATED BY DEFAULT AS IDENTITY`, and `pragma_table_info` are
/// each driver-specific.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DatabaseKind {
    Sqlite,
    Postgres,
    MySql,
}

impl DatabaseKind {
    /// Parse the driver from the URL scheme. The set of accepted schemes
    /// mirrors sqlx's `AnyKind::from_str` (src/any/kind.rs). Unknown schemes
    /// default to `Sqlite` for backwards compatibility — the iLink Hub
    /// desktop default is `sqlite:~/.ilink-hub/ilink-hub.db`, and a typo
    /// in a CLI flag should not refuse to start.
    fn from_url(url: &str) -> Self {
        if url.starts_with("postgres:") || url.starts_with("postgresql:") {
            DatabaseKind::Postgres
        } else if url.starts_with("mysql:") || url.starts_with("mariadb:") {
            DatabaseKind::MySql
        } else {
            DatabaseKind::Sqlite
        }
    }
}

pub struct Store {
    pool: AnyPool,
    kind: DatabaseKind,
}

impl Store {
    /// Connect to the database and run migrations.
    ///
    /// For SQLite URLs, the database file is created automatically if it does
    /// not exist yet (equivalent to `create_if_missing(true)`).
    pub async fn connect(url: &str) -> Result<Self> {
        sqlx::any::install_default_drivers();

        // Parse the driver from the URL scheme prefix BEFORE opening the
        // pool. The migrator needs the kind to pick driver-specific SQL
        // (INSERT...ON CONFLICT...RETURNING is SQLite/Postgres; MySQL uses
        // INSERT IGNORE; AUTOINCREMENT is SQLite-only, etc.). The URL
        // scheme is the only reliable driver signal — runtime probing via
        // `SELECT current_database()` is unreliable because both SQLite AND
        // MySQL reject that function (SQLite has no concept; MySQL uses
        // `database()` instead). See F-M3-01 in the m3 review-findings.
        let kind = DatabaseKind::from_url(url);
        let is_sqlite = kind == DatabaseKind::Sqlite;

        // For SQLite we must ensure the file (and its parent directory) exist
        // before connecting, because sqlx's AnyPool does not set
        // `create_if_missing` by default and will return SQLITE_CANTOPEN (14).
        if is_sqlite {
            let url_owned = url.to_string();
            tokio::time::timeout(
                std::time::Duration::from_secs(10),
                tokio::task::spawn_blocking(move || Self::ensure_sqlite_file(&url_owned)),
            )
            .await
            .map_err(|_| anyhow::anyhow!("ensure_sqlite_file timed out after 10s"))?
            .map_err(|e| anyhow::anyhow!("spawn_blocking failed: {e}"))??;
        }

        // For SQLite :memory: databases each new physical connection gets its own
        // fresh (empty) database. To ensure DDL and DML share the same in-memory
        // instance we pin the pool to a single connection.
        //
        // For file-type SQLite, the same single-connection pin is required to
        // avoid SQLITE_BUSY (5) errors: SQLite's file-level write lock means a
        // long write transaction (e.g. `find_or_create_vctx`) and a
        // concurrent read (e.g. `get_active_session_name`) executed on two
        // different physical connections race on the same lock.
        //
        // We explicitly set `busy_timeout = 5000` (5s) and `journal_mode = WAL`
        // via an `after_connect` callback so the behaviour is explicit rather
        // than relying on sqlx internal defaults that may change across
        // versions. WAL mode improves crash safety and write throughput
        // (writes do not block reads); on :memory: databases both PRAGMAs
        // are accepted but have no effect.
        let pool = if is_sqlite {
            sqlx::pool::PoolOptions::<sqlx::Any>::new()
                .max_connections(1)
                .after_connect(|conn, _meta| {
                    Box::pin(async move {
                        sqlx::query("PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000")
                            .execute(&mut *conn)
                            .await?;
                        Ok(())
                    })
                })
                .connect(url)
                .await?
        } else {
            AnyPool::connect(url).await?
        };
        let store = Self { pool, kind };
        store.run_migrations().await?;
        Ok(store)
    }

    #[cfg(test)]
    pub fn pool(&self) -> &sqlx::AnyPool {
        &self.pool
    }

    /// Extract the file path from a SQLite URL and create the file + parent
    /// directories if they do not already exist.
    fn ensure_sqlite_file(url: &str) -> Result<()> {
        // Strip the "sqlite:" scheme prefix; handle the optional // or ///
        let path_part = url
            .strip_prefix("sqlite:///")
            .or_else(|| url.strip_prefix("sqlite://"))
            .or_else(|| url.strip_prefix("sqlite:"))
            .unwrap_or("");

        // Drop any query string (e.g. "?mode=rwc")
        let path_str = path_part.split('?').next().unwrap_or("").trim();

        // Skip in-memory databases (:memory: or empty)
        if path_str.is_empty() || path_str == ":memory:" {
            return Ok(());
        }

        let path = std::path::Path::new(path_str);
        if let Some(parent) = path.parent() {
            if !parent.as_os_str().is_empty() {
                std::fs::create_dir_all(parent)?;
            }
        }
        if !path.exists() {
            match std::fs::OpenOptions::new()
                .create_new(true)
                .write(true)
                .open(path)
            {
                Ok(_) => {}
                Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => {
                    // Another process created the file between our `exists()`
                    // check and `create_new()`; the file exists now — no
                    // truncation, no data loss.
                }
                Err(e) => return Err(e.into()),
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod store_tests;
