//! Database persistence layer.
//! Uses sqlx with runtime driver selection via `DATABASE_URL`:
//!   sqlite:~/.ilink-hub/ilink-hub.db → SQLite (default, file created if missing)
//!   postgres://user:pass@host/db      → PostgreSQL
//!   mysql://user:pass@host/db         → MySQL

use anyhow::Result;
use sqlx::AnyPool;

/// Whitelist check used by SQLite `pragma_table_info` splicing: the table
/// and column names must contain only identifier characters, so the
/// interpolated string cannot smuggle SQL.
#[allow(dead_code)]
fn is_safe_identifier(s: &str) -> bool {
    !s.is_empty() && s.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// Backend driver. Parsed from the URL scheme prefix in `Store::connect`
/// (sqlite: / postgres: / mysql:). The migration runner needs this to
/// pick the right SQL dialect for `try_claim_migration`, the v5 `id` column
/// clause, and the `column_exists` pre-check — `ON CONFLICT ... RETURNING`,
/// `GENERATED BY DEFAULT AS IDENTITY`, and `pragma_table_info` are
/// each driver-specific.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DatabaseKind {
    Sqlite,
    Postgres,
    MySql,
}

impl DatabaseKind {
    /// Parse the driver from the URL scheme. The set of accepted schemes
    /// mirrors sqlx's `AnyKind::from_str` (src/any/kind.rs). Unknown schemes
    /// default to `Sqlite` for backwards compatibility — the iLink Hub
    /// desktop default is `sqlite:~/.ilink-hub/ilink-hub.db`, and a typo
    /// in a CLI flag should not refuse to start.
    fn from_url(url: &str) -> Self {
        if url.starts_with("postgres:") || url.starts_with("postgresql:") {
            DatabaseKind::Postgres
        } else if url.starts_with("mysql:") || url.starts_with("mariadb:") {
            DatabaseKind::MySql
        } else {
            DatabaseKind::Sqlite
        }
    }
}

pub struct Store {
    pool: AnyPool,
    kind: DatabaseKind,
}

pub mod clients;
pub mod context;
pub mod credentials;
pub mod messages;
pub mod migrations;
pub mod sessions;

pub use clients::ClientRow;
pub use messages::MessageRow;
pub use sessions::{BackendSessionRow, SessionStatusEntry};

impl Store {
    /// Connect to the database and run migrations.
    ///
    /// For SQLite URLs, the database file is created automatically if it does
    /// not exist yet (equivalent to `create_if_missing(true)`).
    pub async fn connect(url: &str) -> Result<Self> {
        sqlx::any::install_default_drivers();

        // Parse the driver from the URL scheme prefix BEFORE opening the
        // pool. The migrator needs the kind to pick driver-specific SQL
        // (INSERT...ON CONFLICT...RETURNING is SQLite/Postgres; MySQL uses
        // INSERT IGNORE; AUTOINCREMENT is SQLite-only, etc.). The URL
        // scheme is the only reliable driver signal — runtime probing via
        // `SELECT current_database()` is unreliable because both SQLite AND
        // MySQL reject that function (SQLite has no concept; MySQL uses
        // `database()` instead). See F-M3-01 in the m3 review-findings.
        let kind = DatabaseKind::from_url(url);
        let is_sqlite = kind == DatabaseKind::Sqlite;

        // For SQLite we must ensure the file (and its parent directory) exist
        // before connecting, because sqlx's AnyPool does not set
        // `create_if_missing` by default and will return SQLITE_CANTOPEN (14).
        if is_sqlite {
            let url_owned = url.to_string();
            tokio::time::timeout(
                std::time::Duration::from_secs(10),
                tokio::task::spawn_blocking(move || Self::ensure_sqlite_file(&url_owned)),
            )
            .await
            .map_err(|_| anyhow::anyhow!("ensure_sqlite_file timed out after 10s"))?
            .map_err(|e| anyhow::anyhow!("spawn_blocking failed: {e}"))??;
        }

        // For SQLite :memory: databases each new physical connection gets its own
        // fresh (empty) database. To ensure DDL and DML share the same in-memory
        // instance we pin the pool to a single connection.
        //
        // For file-type SQLite, the same single-connection pin is required to
        // avoid SQLITE_BUSY (5) errors: SQLite's file-level write lock means a
        // long write transaction (e.g. `find_or_create_vctx`) and a
        // concurrent read (e.g. `get_active_session_name`) executed on two
        // different physical connections race on the same lock.
        //
        // We explicitly set `busy_timeout = 5000` (5s) and `journal_mode = WAL`
        // via an `after_connect` callback so the behaviour is explicit rather
        // than relying on sqlx internal defaults that may change across
        // versions. WAL mode improves crash safety and write throughput
        // (writes do not block reads); on :memory: databases both PRAGMAs
        // are accepted but have no effect.
        let pool = if is_sqlite {
            sqlx::pool::PoolOptions::<sqlx::Any>::new()
                .max_connections(1)
                .after_connect(|conn, _meta| {
                    Box::pin(async move {
                        sqlx::query("PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000")
                            .execute(&mut *conn)
                            .await?;
                        Ok(())
                    })
                })
                .connect(url)
                .await?
        } else {
            AnyPool::connect(url).await?
        };
        let store = Self { pool, kind };
        store.run_migrations().await?;
        Ok(store)
    }

    #[cfg(test)]
    pub fn pool(&self) -> &sqlx::AnyPool {
        &self.pool
    }

    /// Extract the file path from a SQLite URL and create the file + parent
    /// directories if they do not already exist.
    fn ensure_sqlite_file(url: &str) -> Result<()> {
        // Strip the "sqlite:" scheme prefix; handle the optional // or ///
        let path_part = url
            .strip_prefix("sqlite:///")
            .or_else(|| url.strip_prefix("sqlite://"))
            .or_else(|| url.strip_prefix("sqlite:"))
            .unwrap_or("");

        // Drop any query string (e.g. "?mode=rwc")
        let path_str = path_part.split('?').next().unwrap_or("").trim();

        // Skip in-memory databases (:memory: or empty)
        if path_str.is_empty() || path_str == ":memory:" {
            return Ok(());
        }

        let path = std::path::Path::new(path_str);
        if let Some(parent) = path.parent() {
            if !parent.as_os_str().is_empty() {
                std::fs::create_dir_all(parent)?;
            }
        }
        if !path.exists() {
            match std::fs::OpenOptions::new()
                .create_new(true)
                .write(true)
                .open(path)
            {
                Ok(_) => {}
                Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => {
                    // Another process created the file between our `exists()`
                    // check and `create_new()`; the file exists now — no
                    // truncation, no data loss.
                }
                Err(e) => return Err(e.into()),
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod store_tests {
    use super::*;

    /// After `Store::connect`, all v1-v5 migrations must have been applied.
    #[tokio::test]
    async fn test_schema_version_tracking() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");

        // All five migrations must be applied after a fresh connect.
        let version = store
            .get_current_version()
            .await
            .expect("get_current_version");
        assert_eq!(
            version, 5,
            "expected all 5 migrations to be applied on a fresh DB"
        );

        for v in 1..=5 {
            let applied = store.is_migration_run(v).await.expect("is_migration_run");
            assert!(applied, "migration v{v} should be marked as applied");
        }

        // Version 0 is not used in the current scheme.
        let run_0 = store.is_migration_run(0).await.expect("is_migration_run");
        assert!(
            !run_0,
            "version 0 is not a real migration and must not be set"
        );
    }

    /// Running `Store::connect` twice on the same in-memory database must not fail.
    /// This is the idempotency guarantee: all migrations use `IF NOT EXISTS` guards
    /// and `ON CONFLICT DO NOTHING`, so repeated runs are safe.
    #[tokio::test]
    async fn test_migration_idempotency() {
        let store = Store::connect("sqlite::memory:")
            .await
            .expect("first connect");

        // Manually call run_migrations again to simulate a re-run.
        store
            .run_migrations()
            .await
            .expect("second run_migrations must be idempotent");

        let version = store
            .get_current_version()
            .await
            .expect("get_current_version");
        assert_eq!(version, 5, "version must remain 5 after idempotent re-run");
    }

    /// Simulates a database that was bootstrapped at v2 (e.g. an older deployment
    /// that never ran v3–v5). After calling `run_migrations`, v3-v5 must be applied
    /// and v1-v2 must remain intact.
    #[tokio::test]
    async fn test_migration_incremental_from_v2() {
        // Bootstrap with only v1-v2 tables and schema_version table set to v2.
        let store = {
            let pool = sqlx::pool::PoolOptions::<sqlx::Any>::new()
                .max_connections(1)
                .connect("sqlite::memory:")
                .await
                .expect("pool");
            let s = Store {
                pool,
                kind: DatabaseKind::Sqlite,
            };

            // Manually create the tables that v1 and v2 would create.
            s.ddl(
                "CREATE TABLE IF NOT EXISTS schema_version (
                    version     INTEGER PRIMARY KEY,
                    migrated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
                )",
            )
            .await
            .expect("schema_version");
            s.ddl(
                "CREATE TABLE IF NOT EXISTS clients (
                    vtoken TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE,
                    label TEXT, created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP), last_seen TEXT
                )",
            )
            .await
            .expect("clients");
            s.ddl(
                "CREATE TABLE IF NOT EXISTS routing_state (
                    from_user TEXT PRIMARY KEY,
                    active_vtoken TEXT NOT NULL,
                    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
                )",
            )
            .await
            .expect("routing_state");
            s.ddl(
                "CREATE TABLE IF NOT EXISTS context_token_map (
                    vctx TEXT PRIMARY KEY, real_ctx TEXT NOT NULL,
                    peer_user_id TEXT NOT NULL DEFAULT '', expires_at TEXT
                )",
            )
            .await
            .expect("context_token_map");
            s.ddl(
                "CREATE TABLE IF NOT EXISTS bot_credentials (
                    id INTEGER PRIMARY KEY, token TEXT NOT NULL,
                    base_url TEXT NOT NULL DEFAULT 'https://ilinkai.weixin.qq.com',
                    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
                )",
            )
            .await
            .expect("bot_credentials");
            s.ddl(
                "CREATE TABLE IF NOT EXISTS backend_sessions_v2 (
                    vctx TEXT NOT NULL, vtoken TEXT NOT NULL,
                    session_name TEXT NOT NULL, backend_session_id TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
                    PRIMARY KEY (vctx, vtoken, session_name)
                )",
            )
            .await
            .expect("backend_sessions_v2");
            s.ddl(
                "CREATE TABLE IF NOT EXISTS active_sessions (
                    vctx TEXT NOT NULL, vtoken TEXT NOT NULL,
                    session_name TEXT NOT NULL DEFAULT 'default',
                    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
                    PRIMARY KEY (vctx, vtoken)
                )",
            )
            .await
            .expect("active_sessions");

            // Mark v1 and v2 as already applied.
            s.record_migration_run(1).await.expect("mark v1");
            s.record_migration_run(2).await.expect("mark v2");

            s
        };

        // v3-v5 should not yet be applied.
        assert!(!store.is_migration_run(3).await.unwrap());
        assert!(!store.is_migration_run(4).await.unwrap());
        assert!(!store.is_migration_run(5).await.unwrap());

        // Running migrations now must apply v3-v5.
        store.run_migrations().await.expect("incremental migration");

        let version = store.get_current_version().await.unwrap();
        assert_eq!(version, 5, "must reach v5 after incremental migration");

        for v in 1..=5 {
            assert!(
                store.is_migration_run(v).await.unwrap(),
                "v{v} must be marked applied"
            );
        }
    }

    #[tokio::test]
    async fn migration_runs_on_in_memory_sqlite() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");
        // If migration ran, these should succeed
        let r = store.list_clients().await;
        assert!(r.is_ok(), "list_clients failed: {:?}", r.err());
        let r = store.list_recent_context_tokens(5).await;
        assert!(
            r.is_ok(),
            "list_recent_context_tokens failed: {:?}",
            r.err()
        );
    }

    /// Regression test for DB-01: file-type SQLite must pin the pool to a
    /// single connection so that concurrent write transactions and reads
    /// from different physical connections cannot race on the SQLite file
    /// lock and return `SQLITE_BUSY` (5).
    ///
    /// Before the fix, `AnyPool::connect(url)` for `sqlite:/path/to.db`
    /// defaulted to 10 connections. With multiple tasks issuing write
    /// transactions (`find_or_create_vctx`,
    /// `set_active_session_name`) and reads (`get_active_session_name`)
    /// concurrently, two physical connections would race on the
    /// file-level EXCLUSIVE write lock; once a writer's lock-hold time
    /// exceeded the default `busy_timeout` (5s), a competing transaction
    /// would surface `SQLITE_BUSY`. The fix collapses the pool to
    /// `max_connections(1)` for any `sqlite:` URL, which serializes
    /// transactions on a single connection (no second connection means
    /// no second contender for the file lock).
    #[tokio::test(flavor = "multi_thread", worker_threads = 8)]
    async fn file_sqlite_serializes_concurrent_read_and_write_without_busy() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let db_path = tmp.path().join("concurrent.db");
        let url = format!("sqlite:{}", db_path.display());
        let store = std::sync::Arc::new(Store::connect(&url).await.expect("connect"));

        // The fix is structural: the pool must be sized to a single
        // connection for any sqlite URL. Verify the invariant first
        // (fast, deterministic, pinpoints regressions), then run a
        // multi-task mixed read/write workload that would surface
        // SQLITE_BUSY on a multi-connection pool with a non-default
        // (small) busy_timeout. The structural assertion is the
        // canonical regression guard.
        assert_eq!(
            store.pool.options().get_max_connections(),
            1,
            "SQLite pool must be pinned to max_connections(1) to avoid SQLITE_BUSY"
        );

        // Seed one row so the read path has a target.
        store
            .find_or_create_vctx("peer-seed", None, "real-ctx-seed")
            .await
            .expect("seed");
        store
            .set_active_session_name("vctx-seed", "vtoken-seed", "default")
            .await
            .expect("seed active session");

        let mut handles = Vec::new();

        // Write task: hammer find_or_create_vctx with many unique peers to exercise
        // concurrent writes and increase the chance of a write/write race on the file lock.
        for w in 0..8 {
            let store = std::sync::Arc::clone(&store);
            handles.push(tokio::spawn(async move {
                for i in 0..20 {
                    for j in 0..10 {
                        store
                            .find_or_create_vctx(
                                &format!("peer-w{w}-i{i}-j{j}"),
                                None,
                                &format!("real-ctx-w{w}-i{i}-j{j}"),
                            )
                            .await
                            .expect("find_or_create_vctx must not fail");
                    }
                }
            }));
        }

        // Single-row write task: hammer set_active_session_name (a
        // write transaction) on a different row each time so we are
        // exercising the same physical-connection file-lock path.
        for w in 0..4 {
            let store = std::sync::Arc::clone(&store);
            handles.push(tokio::spawn(async move {
                for i in 0..200 {
                    let vctx = format!("vctx-active-w{w}-i{i}");
                    let vtoken = format!("vtoken-active-w{w}-i{i}");
                    store
                        .set_active_session_name(&vctx, &vtoken, "default")
                        .await
                        .expect("set_active_session_name must not fail");
                }
            }));
        }

        // Reader task: hammer get_active_session_name.
        for r in 0..4 {
            let store = std::sync::Arc::clone(&store);
            handles.push(tokio::spawn(async move {
                for i in 0..200 {
                    let vtoken = format!("ignored-vtoken-r{r}-i{i}");
                    let name = store
                        .get_active_session_name("vctx-seed", &vtoken)
                        .await
                        .expect("read must not fail");
                    assert_eq!(name, "default");
                }
            }));
        }

        for h in handles {
            h.await.expect("task join");
        }
    }

    #[tokio::test]
    async fn test_sync_02_upsert_client_updates_routing_state() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");

        // Register client "bridge-a" with "vtoken-1"
        store
            .upsert_client("vtoken-1", "bridge-a", None)
            .await
            .unwrap();

        // Set route for user "alice" to "vtoken-1"
        store.set_route("alice", "vtoken-1").await.unwrap();

        // Verify route is set
        let route = store.get_route("alice").await.unwrap();
        assert_eq!(route, Some("vtoken-1".to_string()));

        // Re-register client "bridge-a" with "vtoken-2"
        store
            .upsert_client("vtoken-2", "bridge-a", None)
            .await
            .unwrap();

        // Verify route is updated to "vtoken-2"
        let route = store.get_route("alice").await.unwrap();
        assert_eq!(route, Some("vtoken-2".to_string()));
    }

    #[tokio::test]
    async fn test_db_03_get_hub_ext_batch_query() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");

        // Insert some session data
        store
            .set_active_session_name("vctx-1", "vtoken-1", "session-1")
            .await
            .unwrap();
        store
            .set_active_session_name("vctx-2", "vtoken-2", "session-2")
            .await
            .unwrap();

        store
            .set_backend_session("vctx-1", "vtoken-1", "session-1", "sid-1")
            .await
            .unwrap();
        store
            .set_backend_session("vctx-2", "vtoken-2", "session-2", "sid-2")
            .await
            .unwrap();

        let pairs = vec![
            ("vctx-1".to_string(), "vtoken-1".to_string()),
            ("vctx-2".to_string(), "vtoken-2".to_string()),
            ("vctx-3".to_string(), "vtoken-3".to_string()), // nonexistent
        ];

        let result = store.get_hub_ext_batch(&pairs).await.unwrap();
        assert_eq!(result.len(), 3);
        assert_eq!(
            result.get(&("vctx-1".to_string(), "vtoken-1".to_string())),
            Some(&("session-1".to_string(), Some("sid-1".to_string())))
        );
        assert_eq!(
            result.get(&("vctx-2".to_string(), "vtoken-2".to_string())),
            Some(&("session-2".to_string(), Some("sid-2".to_string())))
        );
        assert_eq!(
            result.get(&("vctx-3".to_string(), "vtoken-3".to_string())),
            Some(&("default".to_string(), None))
        );
    }

    #[tokio::test]
    async fn test_db_02_find_or_create_vctx_multiple_peers() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");

        for i in 0..55 {
            store
                .find_or_create_vctx(&format!("peer-{i}"), None, &format!("real-{i}"))
                .await
                .unwrap();
        }

        let recent = store.list_recent_context_tokens(100).await.unwrap();
        assert_eq!(recent.len(), 55);
    }

    #[tokio::test]
    async fn test_sync_02_upsert_client_concurrent_adversarial() {
        // Create a temporary database in target/ directory of the workspace
        let temp_dir = tempfile::Builder::new()
            .prefix("test_concurrent_db")
            .tempdir_in("target")
            .unwrap();
        let db_path = temp_dir.path().join("test.db");
        let db_url = format!("sqlite:{}", db_path.to_str().unwrap());

        let store = Store::connect(&db_url).await.expect("connect");

        // Initial setup: register client "bridge-concurrent" with "vtoken-initial"
        store
            .upsert_client("vtoken-initial", "bridge-concurrent", None)
            .await
            .unwrap();

        // Set route for user "alice" to "vtoken-initial"
        store.set_route("alice", "vtoken-initial").await.unwrap();

        // Now run multiple concurrent upserts of client "bridge-concurrent"
        let num_concurrency = 20;
        let mut handles = vec![];

        let store = std::sync::Arc::new(store);

        for i in 0..num_concurrency {
            let store_clone = store.clone();
            let vtoken = format!("vtoken-{}", i);
            let handle = tokio::spawn(async move {
                store_clone
                    .upsert_client(&vtoken, "bridge-concurrent", None)
                    .await
            });
            handles.push(handle);
        }

        // Wait for all tasks to complete
        for h in handles {
            h.await.unwrap().unwrap();
        }

        // Retrieve the final vtoken in the clients table
        let clients = store.list_clients().await.unwrap();
        let final_client_vtoken = clients
            .iter()
            .find(|c| c.name == "bridge-concurrent")
            .map(|c| c.vtoken.clone())
            .unwrap();

        // Retrieve the route for "alice"
        let final_route = store.get_route("alice").await.unwrap().unwrap();

        // Under race conditions in the old implementation, final_route would be stale
        // while final_client_vtoken would be the last committed vtoken.
        // We assert that they must be identical.
        assert_eq!(final_route, final_client_vtoken);
    }

    // ─── Adversarial regression tests for the review findings ─────────────────
    //
    // Each test below pins down a specific finding from the M1 review. They are
    // grouped by the finding they cover, not by topic, so a future reader
    // hunting for "what was F-M1-02?" can grep and land here.

    /// F-M1-01 / F-M1-04 / F-M3-02: Two TRULY concurrent `Store::connect`
    /// calls against the same file-backed SQLite database must BOTH succeed
    /// and converge to `get_current_version() == 5`. The two connect tasks
    /// are spawned via `tokio::join!` so they race in flight — the M3 review
    /// (F-M3-02) flagged that the prior version of this test ran sequentially
    /// (one connect awaited before the next started) and so did NOT exercise
    /// the concurrent-claim path that `try_claim_migration` is designed to
    /// close. With `tokio::join!` both connect tasks are polling the runtime
    /// scheduler at once, and the only thing serialising them is the
    /// atomic `try_claim_migration` `INSERT ... ON CONFLICT DO NOTHING
    /// RETURNING` (SQLite/Postgres) or `INSERT IGNORE` (MySQL) primitive.
    #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
    async fn adversarial_concurrent_store_connect_succeeds_and_converges() {
        sqlx::any::install_default_drivers();
        let tmp = tempfile::tempdir().expect("tempdir");
        let url = format!("sqlite:{}/concurrent.db", tmp.path().display());
        let url1 = url.clone();
        let url2 = url.clone();
        // tokio::join! polls both futures on the same task; the multi-thread
        // runtime above lets them run in parallel. Both connect() calls are
        // in flight at the same time; the SQLite single-connection pin
        // serialises them on the file lock, but the claim primitive
        // (try_claim_migration) is the load-bearing piece — without it the
        // v3 / v4 DDL would double-run.
        let (s1, s2) = tokio::join!(async move { Store::connect(&url1).await }, async move {
            Store::connect(&url2).await
        },);
        let s1 = s1.expect("connect #1 must succeed");
        let s2 = s2.expect("connect #2 must succeed");
        assert_eq!(
            s1.get_current_version().await.unwrap(),
            5,
            "writer #1 must see all v1-v5 applied"
        );
        assert_eq!(
            s2.get_current_version().await.unwrap(),
            5,
            "writer #2 must see all v1-v5 applied"
        );
        // The whole schema must be usable from both writers — no half-applied
        // tables, no missing indexes.
        for s in [&s1, &s2] {
            assert!(s.list_clients().await.is_ok());
            assert!(s.list_recent_context_tokens(1).await.is_ok());
        }
    }

    /// F-M1-01 / F-M3-02: 10 TRULY concurrent `Store::connect` callers (each
    /// spawned via `tokio::spawn` and joined via `futures::join_all`) must
    /// all converge to version 5. The prior version of this test was
    /// sequential (a `for` loop awaiting each connect before starting the
    /// next) and so did NOT exercise the concurrent-claim path.
    /// `tokio::spawn` + `join_all` puts all 10 connects in flight at once;
    /// `try_claim_migration` is the only thing keeping the v1-v5 DDL from
    /// running multiple times.
    #[tokio::test(flavor = "multi_thread", worker_threads = 8)]
    async fn adversarial_many_concurrent_connects_converge() {
        sqlx::any::install_default_drivers();
        let tmp = tempfile::tempdir().expect("tempdir");
        let url = format!("sqlite:{}/many.db", tmp.path().display());
        let mut handles = Vec::with_capacity(10);
        for i in 0..10 {
            let url = url.clone();
            handles.push(tokio::spawn(async move {
                let mut last_err = String::new();
                for attempt in 0..5 {
                    match Store::connect(&url).await {
                        Ok(s) => return Ok(s),
                        Err(e) => {
                            let is_busy = e
                                .downcast_ref::<sqlx::Error>()
                                .map(|se| {
                                    matches!(
                                        se,
                                        sqlx::Error::Database(ref db_err)
                                            if db_err.code().as_deref() == Some("5")
                                    )
                                })
                                .unwrap_or(false);
                            last_err = format!("{e}");
                            if is_busy && attempt < 4 {
                                tokio::time::sleep(std::time::Duration::from_millis(300)).await;
                                continue;
                            }
                        }
                    }
                }
                Err(format!("connect #{i} failed after retries: {last_err}"))
            }));
        }
        let mut stores = Vec::with_capacity(handles.len());
        for h in handles {
            stores.push(
                h.await
                    .expect("task join")
                    .unwrap_or_else(|e| panic!("{e}")),
            );
        }
        for (i, s) in stores.iter().enumerate() {
            assert_eq!(
                s.get_current_version().await.unwrap(),
                5,
                "connect #{i} must see all v1-v5 applied"
            );
        }
    }

    /// F-M1-02: v4's "column already exists" branch is now driven by an
    /// `information_schema.columns` pre-check, not by an error-string match.
    /// Simulate the pre-schema_version deployment state (v1+v2 tables exist,
    /// `created_at` already present, v1+v2 marked run) and verify the v4 path
    /// is silently skipped (no error, no DDL) and the index is created.
    #[tokio::test]
    async fn adversarial_v4_skips_alter_when_column_already_present() {
        // Install drivers so the manual pool below can use them.
        sqlx::any::install_default_drivers();
        let pool = sqlx::pool::PoolOptions::<sqlx::Any>::new()
            .max_connections(1)
            .connect("sqlite::memory:")
            .await
            .expect("pool");
        let store = Store {
            pool,
            kind: DatabaseKind::Sqlite,
        };
        // Bootstrap the same v1+v2 state as `test_migration_incremental_from_v2`.
        store
            .ddl(
                "CREATE TABLE IF NOT EXISTS schema_version (
                    version     INTEGER PRIMARY KEY,
                    migrated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
                )",
            )
            .await
            .expect("schema_version");
        store
            .ddl(
                "CREATE TABLE IF NOT EXISTS clients (
                    vtoken TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE,
                    label TEXT, created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP), last_seen TEXT
                )",
            )
            .await
            .expect("clients");
        store
            .ddl(
                "CREATE TABLE IF NOT EXISTS routing_state (
                    from_user TEXT PRIMARY KEY,
                    active_vtoken TEXT NOT NULL,
                    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
                )",
            )
            .await
            .expect("routing_state");
        // The legacy state: `created_at` already present, but schema_version
        // doesn't yet know about v4.
        store
            .ddl(
                "CREATE TABLE IF NOT EXISTS context_token_map (
                    vctx TEXT PRIMARY KEY, real_ctx TEXT NOT NULL,
                    peer_user_id TEXT NOT NULL DEFAULT '', expires_at TEXT,
                    created_at TEXT
                )",
            )
            .await
            .expect("context_token_map (with created_at)");
        store
            .ddl(
                "CREATE TABLE IF NOT EXISTS bot_credentials (
                    id INTEGER PRIMARY KEY, token TEXT NOT NULL,
                    base_url TEXT NOT NULL DEFAULT 'https://ilinkai.weixin.qq.com',
                    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
                )",
            )
            .await
            .expect("bot_credentials");
        store
            .ddl(
                "CREATE TABLE IF NOT EXISTS backend_sessions_v2 (
                    vctx TEXT NOT NULL, vtoken TEXT NOT NULL,
                    session_name TEXT NOT NULL, backend_session_id TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
                    PRIMARY KEY (vctx, vtoken, session_name)
                )",
            )
            .await
            .expect("backend_sessions_v2");
        store
            .ddl(
                "CREATE TABLE IF NOT EXISTS active_sessions (
                    vctx TEXT NOT NULL, vtoken TEXT NOT NULL,
                    session_name TEXT NOT NULL DEFAULT 'default',
                    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
                    PRIMARY KEY (vctx, vtoken)
                )",
            )
            .await
            .expect("active_sessions");
        store.record_migration_run(1).await.expect("mark v1");
        store.record_migration_run(2).await.expect("mark v2");

        // Run migrations: v3, v4, v5 must all run, and v4 must NOT fail.
        store
            .run_migrations()
            .await
            .expect("run_migrations must succeed");

        // All v1-v5 must be marked applied.
        for v in 1..=5 {
            assert!(
                store.is_migration_run(v).await.unwrap(),
                "v{v} must be marked applied after run_migrations"
            );
        }
        // The pre-check took the "skip" branch — verify by reading the catalog
        // directly. If the column were missing, the v4 path would have re-added
        // it. Reading the catalog also confirms we did not accidentally drop
        // the legacy column.
        assert!(
            store
                .column_exists("context_token_map", "created_at")
                .await
                .unwrap(),
            "created_at must still exist (we only skip the ALTER, never drop)"
        );
    }

    /// F-M1-03: a column-decode error on `get_current_version` must be
    /// propagated, not swallowed. We seed the table with a TEXT value that
    /// SQLite accepts (via type affinity) but sqlx refuses to decode as
    /// `i32`, call `get_current_version`, and assert the result is `Err`
    /// rather than a silent `Ok(0)`.
    ///
    /// Also pins down the M3 lock-sentinel filter: the migration runner
    /// stores its `MIGRATION_LOCK_VERSION = i32::MAX` row alongside the
    /// per-step rows, and `get_current_version` must exclude that row from
    /// its result so external callers see the real schema version (e.g. 5),
    /// not the lock sentinel.
    #[tokio::test]
    async fn adversarial_get_current_version_propagates_decode_error() {
        sqlx::any::install_default_drivers();
        let pool = sqlx::pool::PoolOptions::<sqlx::Any>::new()
            .max_connections(1)
            .connect("sqlite::memory:")
            .await
            .expect("pool");
        let store = Store {
            pool,
            kind: DatabaseKind::Sqlite,
        };
        store
            .ddl(
                "CREATE TABLE IF NOT EXISTS schema_version (
                    version     INTEGER PRIMARY KEY,
                    migrated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
                )",
            )
            .await
            .expect("schema_version");
        // (1) Lock sentinel filter: insert a row at the lock sentinel
        // value (i32::MAX). The new `get_current_version` filter
        // excludes it. The table appears "empty" to external callers.
        sqlx::query("INSERT INTO schema_version (version) VALUES ($1)")
            .bind(i32::MAX)
            .execute(&store.pool)
            .await
            .expect("insert lock sentinel");
        let res = store.get_current_version().await;
        assert_eq!(
            res.ok(),
            Some(0),
            "get_current_version must exclude the lock sentinel and return 0 for an empty (real-version) table"
        );

        // (2) F-M1-03 regression: the `schema_version.version` column is
        // `INTEGER PRIMARY KEY`, which SQLite enforces strictly — text values
        // are rejected at the driver level with "datatype mismatch" (code 20).
        // This means the pathological scenario the original test intended to
        // simulate (text stored via type affinity) CANNOT occur in practice
        // with this schema: the constraint itself is the guard.
        // We verify this defence-in-depth by confirming the insert IS rejected.
        sqlx::query("DELETE FROM schema_version WHERE version = $1")
            .bind(i32::MAX)
            .execute(&store.pool)
            .await
            .expect("delete lock sentinel");
        let bad_insert =
            sqlx::query("INSERT INTO schema_version (version) VALUES ('not-a-number')")
                .execute(&store.pool)
                .await;
        assert!(
            bad_insert.is_err(),
            "SQLite INTEGER PRIMARY KEY must reject non-integer insert — F-M1-03 defence-in-depth"
        );
    }

    /// F-M1-07: `is_migration_run` / `get_current_version` / `try_claim_migration`
    /// must accept version values used by the migration runner and the test
    /// surface. A negative version is not a real migration but the API must
    /// not crash. `get_current_version` and `try_claim_migration` follow the
    /// same shape — they bind the version and pass it through to the driver.
    /// This test pins down the boundary behaviour for the version = 0 and
    /// negative cases so a future refactor that tightens input validation
    /// has a clear contract to keep.
    #[tokio::test]
    async fn adversarial_version_api_boundaries() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");
        // is_migration_run(0): not applied, no error.
        assert!(!store.is_migration_run(0).await.unwrap());
        // is_migration_run(-1): not applied, no error.
        assert!(!store.is_migration_run(-1).await.unwrap());
        // get_current_version: 5 (the highest applied).
        assert_eq!(store.get_current_version().await.unwrap(), 5);
    }

    /// F-M1-08: `try_claim_migration` is the atomic primitive. Two concurrent
    /// claims for the SAME version on a multi-connection-shaped scenario
    /// (simulated by issuing two claims on the same store) must result in
    /// exactly one `true` and one `false`. This is the unit-level guard
    /// for the M1 invariant; the end-to-end variant is the
    /// `adversarial_concurrent_store_connect_succeeds_and_converges` test.
    ///
    /// On SQLite with `max_connections(1)` the SQL is serialised by the
    /// connection, so the second claim always observes the first's row. On
    /// Postgres / MySQL the `ON CONFLICT DO NOTHING RETURNING` clause is the
    /// thing that serialises the claim — the second `INSERT` is a no-op
    /// (returns no row). The test works on SQLite because the storage path
    /// is the same `INSERT ... ON CONFLICT DO NOTHING RETURNING` SQL.
    #[tokio::test]
    async fn adversarial_try_claim_is_mutually_exclusive() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");
        // Manually delete v5's claim row so we can race for it.
        sqlx::query("DELETE FROM schema_version WHERE version = 5")
            .execute(&store.pool)
            .await
            .expect("delete v5 row");
        // Two back-to-back claims; the second must observe the first's row.
        let first = store.try_claim_migration(5).await.unwrap();
        let second = store.try_claim_migration(5).await.unwrap();
        assert!(first, "first claim must win");
        assert!(!second, "second claim must lose");
    }

    /// F-M3-02 (unit-level): two TRULY concurrent `try_claim_migration`
    /// calls on the same `Store` must produce exactly one `true` and one
    /// `false`. The pre-M3-fix version of the test issued the two claims
    /// back-to-back in a single `async` block, which serialised them on
    /// the same task — the second `await` never started until the first
    /// had returned. The M3 fix uses `tokio::join!` so both futures
    /// poll concurrently on the multi-thread runtime; the claim
    /// primitive (`INSERT ... ON CONFLICT DO NOTHING RETURNING` for
    /// SQLite/Postgres, `INSERT IGNORE` for MySQL) is the only thing
    /// keeping exactly one claim from winning.
    #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
    async fn adversarial_try_claim_is_mutually_exclusive_concurrent() {
        let store = std::sync::Arc::new(Store::connect("sqlite::memory:").await.expect("connect"));
        // Manually delete v5's claim row so we can race for it. Both
        // clones see the same schema_version table; only one insert can
        // win.
        sqlx::query("DELETE FROM schema_version WHERE version = 5")
            .execute(&store.pool)
            .await
            .expect("delete v5 row");
        let s1 = std::sync::Arc::clone(&store);
        let s2 = std::sync::Arc::clone(&store);
        // tokio::join! polls both futures on the same task; the
        // multi-thread runtime above lets them run in parallel. Both
        // INSERTs are in flight at once.
        let (first, second) = tokio::join!(
            async move { s1.try_claim_migration(5).await.unwrap() },
            async move { s2.try_claim_migration(5).await.unwrap() },
        );
        // Exactly one of the two claims must win. The other must see
        // the row already present and return false.
        let wins = [first, second].iter().filter(|w| **w).count();
        assert_eq!(
            wins, 1,
            "exactly one of two concurrent try_claim_migration(5) calls must win; got {first}/{second}"
        );
        // The version row must be present exactly once.
        let rows: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM schema_version WHERE version = 5")
            .fetch_one(&store.pool)
            .await
            .expect("count");
        assert_eq!(rows.0, 1, "exactly one claim row must exist for v5");
    }

    // ─── M2 regression tests ───────────────────────────────────────────────
    //
    // M2 refactors `run_migrations` into per-version `migrate_to_vN` functions.
    // Each step is gated by `try_claim_migration`, the DDL errors propagate
    // via `?` rather than being swallowed, and the schema_version table is
    // updated as a side-effect of the claim. The tests below pin each of
    // those invariants.

    /// F-M2-01: every `migrate_to_vN` is independently callable and updates
    /// `schema_version` only for its own version. Calling v2 alone after a
    /// fresh connect (which has only v0) must record v2 and leave v1, v3,
    /// v4, v5 unmarked.
    #[tokio::test]
    async fn m2_per_version_migrators_update_schema_version_independently() {
        sqlx::any::install_default_drivers();
        let pool = sqlx::pool::PoolOptions::<sqlx::Any>::new()
            .max_connections(1)
            .connect("sqlite::memory:")
            .await
            .expect("pool");
        let store = Store {
            pool,
            kind: DatabaseKind::Sqlite,
        };
        // Bootstrap only the schema_version table — no migrations applied yet.
        store
            .ddl(
                "CREATE TABLE IF NOT EXISTS schema_version (
                    version     INTEGER PRIMARY KEY,
                    migrated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
                )",
            )
            .await
            .expect("schema_version");

        // Run only v2 in isolation.
        store.migrate_to_v2().await.expect("migrate_to_v2");

        // v2 must be marked; v1, v3, v4, v5 must not.
        assert!(
            store.is_migration_run(2).await.unwrap(),
            "v2 must be marked after migrate_to_v2"
        );
        for v in [1, 3, 4, 5] {
            assert!(
                !store.is_migration_run(v).await.unwrap(),
                "v{v} must NOT be marked after running only v2"
            );
        }

        // v2 tables must exist (sanity check the DDL actually ran).
        let row: Option<(String,)> = sqlx::query_as(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='backend_sessions_v2'",
        )
        .fetch_optional(&store.pool)
        .await
        .expect("catalog");
        assert!(
            row.is_some(),
            "backend_sessions_v2 must exist after migrate_to_v2"
        );

        // v1 tables must NOT exist (v1 was not run).
        let row: Option<(String,)> =
            sqlx::query_as("SELECT name FROM sqlite_master WHERE type='table' AND name='clients'")
                .fetch_optional(&store.pool)
                .await
                .expect("catalog");
        assert!(row.is_none(), "clients must NOT exist (v1 was not run)");
    }

    /// F-M2-02: re-running an already-applied migration is a no-op. The
    /// claim returns false, the DDL is skipped, and the schema_version
    /// row is unchanged.
    #[tokio::test]
    async fn m2_migrators_are_idempotent_per_step() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");
        // After connect, all 5 are applied. Re-running each must NOT fail
        // and must NOT touch the schema_version table.
        store.migrate_to_v1().await.expect("v1 re-run");
        store.migrate_to_v2().await.expect("v2 re-run");
        store.migrate_to_v3().await.expect("v3 re-run");
        store.migrate_to_v4().await.expect("v4 re-run");
        store.migrate_to_v5().await.expect("v5 re-run");

        // Still at v5.
        assert_eq!(store.get_current_version().await.unwrap(), 5);
    }

    /// F-M2-03: a DDL failure inside a migrator must propagate as `Err`,
    /// NOT be silently swallowed. We construct a synthetic failure: pre-
    /// create a `context_token_map` whose schema blocks v3's
    /// `CREATE UNIQUE INDEX`. The unique index is rejected when the table
    /// already has duplicate `real_ctx` rows, so the migrator must
    /// surface the underlying driver error.
    #[tokio::test]
    async fn m2_ddl_error_propagates_through_migrator() {
        sqlx::any::install_default_drivers();
        let pool = sqlx::pool::PoolOptions::<sqlx::Any>::new()
            .max_connections(1)
            .connect("sqlite::memory:")
            .await
            .expect("pool");
        let store = Store {
            pool,
            kind: DatabaseKind::Sqlite,
        };
        // Bootstrap the version-tracking table and the v1 schema with
        // duplicated real_ctx values — the v3 unique index cannot be
        // created over a non-unique column.
        store
            .ddl(
                "CREATE TABLE IF NOT EXISTS schema_version (
                    version     INTEGER PRIMARY KEY,
                    migrated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
                )",
            )
            .await
            .expect("schema_version");
        store
            .ddl(
                "CREATE TABLE context_token_map (
                    vctx TEXT PRIMARY KEY, real_ctx TEXT NOT NULL,
                    peer_user_id TEXT NOT NULL DEFAULT '', expires_at TEXT
                )",
            )
            .await
            .expect("context_token_map");
        // Two rows with the same real_ctx → v3's CREATE UNIQUE INDEX fails.
        sqlx::query("INSERT INTO context_token_map (vctx, real_ctx) VALUES ($1, $2)")
            .bind("vctx-1")
            .bind("dup-real")
            .execute(&store.pool)
            .await
            .expect("seed row 1");
        sqlx::query("INSERT INTO context_token_map (vctx, real_ctx) VALUES ($1, $2)")
            .bind("vctx-2")
            .bind("dup-real")
            .execute(&store.pool)
            .await
            .expect("seed row 2");

        // migrate_to_v3 must surface the CREATE UNIQUE INDEX error.
        let result = store.migrate_to_v3().await;
        assert!(
            result.is_err(),
            "migrate_to_v3 must propagate DDL errors, got Ok — F-M2-03 not fixed"
        );
        // The claim row is still inserted (the M1 design writes the row
        // BEFORE the DDL); a subsequent connect will see v3 as claimed
        // and skip the broken step (DBA drops the row manually).
        assert!(
            store.is_migration_run(3).await.unwrap(),
            "v3 claim row is present even though DDL failed"
        );
    }

    /// F-M2-04: `record_migration_run` (the safety-net kept in M1) writes
    /// the row even after the migrator has already claimed the version.
    /// Since `try_claim_migration` already inserts the row, calling
    /// `record_migration_run` again is a no-op. The combined behaviour:
    /// the row is present exactly once, and a second `try_claim_migration`
    /// returns false.
    #[tokio::test]
    async fn m2_claim_and_record_are_consistent_with_schema_version() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");
        // v3 is already applied. A second try_claim must observe the row.
        assert!(
            !store.try_claim_migration(3).await.unwrap(),
            "v3 is already applied; second claim must lose"
        );
        // record_migration_run is a no-op (ON CONFLICT DO NOTHING).
        store
            .record_migration_run(3)
            .await
            .expect("record_migration_run(3) must be a no-op");
        // The version row is still present (we did not delete it).
        assert!(store.is_migration_run(3).await.unwrap());
    }

    /// F-M2-05: invoking a higher-version migrator before a lower one
    /// must not deadlock or produce a partial state. The migrator's
    /// pre-condition is that the schema_version table exists; that's
    /// bootstrapped by `run_migrations`, but a per-version call on a
    /// fresh pool needs the table. We bootstrap manually here, then
    /// run v4 alone: v4 expects `context_token_map` to exist (it
    /// `ADD COLUMN`s onto it), so we also pre-create that table. The
    /// test pins down "running a single migrator on a partial state
    /// with the right pre-conditions is fine and records v4".
    #[tokio::test]
    async fn m2_v4_alone_with_minimal_preconditions() {
        sqlx::any::install_default_drivers();
        let pool = sqlx::pool::PoolOptions::<sqlx::Any>::new()
            .max_connections(1)
            .connect("sqlite::memory:")
            .await
            .expect("pool");
        let store = Store {
            pool,
            kind: DatabaseKind::Sqlite,
        };
        store
            .ddl(
                "CREATE TABLE IF NOT EXISTS schema_version (
                    version     INTEGER PRIMARY KEY,
                    migrated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
                )",
            )
            .await
            .expect("schema_version");
        store
            .ddl(
                "CREATE TABLE context_token_map (
                    vctx TEXT PRIMARY KEY, real_ctx TEXT NOT NULL,
                    peer_user_id TEXT NOT NULL DEFAULT '', expires_at TEXT
                )",
            )
            .await
            .expect("context_token_map");

        // v4 alone: column does not exist, so the ALTER must run.
        store.migrate_to_v4().await.expect("migrate_to_v4");
        assert!(store.is_migration_run(4).await.unwrap());

        // The column was added; the index was created.
        assert!(
            store
                .column_exists("context_token_map", "created_at")
                .await
                .unwrap(),
            "created_at column must exist after v4"
        );
        // Index exists (sqlite_master entry).
        let row: Option<(String,)> = sqlx::query_as(
            "SELECT name FROM sqlite_master \
             WHERE type='index' AND name='idx_context_token_map_created_at'",
        )
        .fetch_optional(&store.pool)
        .await
        .expect("catalog");
        assert!(
            row.is_some(),
            "idx_context_token_map_created_at must exist after v4"
        );
    }

    /// F-M2-06: full `run_migrations` walks all five steps in order and
    /// records v1..=v5 in `schema_version`. This is the headline M2
    /// invariant: any DDL error along the way aborts the walk.
    #[tokio::test]
    async fn m2_run_migrations_records_all_versions_in_order() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");
        // All five versions are present.
        for v in 1..=5 {
            assert!(
                store.is_migration_run(v).await.unwrap(),
                "v{v} must be recorded after run_migrations"
            );
        }
        // get_current_version returns the maximum.
        assert_eq!(store.get_current_version().await.unwrap(), 5);
    }

    /// F-M2-07: `run_migrations` invoked twice in a row must remain
    /// idempotent. The M2 refactor's "early return on claim == false"
    /// shape is what makes this safe; the test pins it down.
    #[tokio::test]
    async fn m2_run_migrations_idempotent_double_call() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");
        // Second call must succeed.
        store.run_migrations().await.expect("second run_migrations");
        // Version stays at 5 (no ghost rows from a third call).
        assert_eq!(store.get_current_version().await.unwrap(), 5);
    }

    /// F-M2-08: each `migrate_to_vN` uses `CURRENT_TIMESTAMP` (not
    /// `datetime('now')`) for any timestamp default. The plan calls for
    /// unifying the DDL on `CURRENT_TIMESTAMP`. We check the catalog for
    /// each table's `sql` field and assert that no DDL contains the
    /// legacy `datetime('now')` form. The catalog on SQLite preserves
    /// the original CREATE TABLE statement, so this is a direct check.
    #[tokio::test]
    async fn m2_ddl_uses_current_timestamp_only() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");
        let rows: Vec<(String,)> =
            sqlx::query_as("SELECT sql FROM sqlite_master WHERE sql IS NOT NULL")
                .fetch_all(&store.pool)
                .await
                .expect("catalog");
        for (sql,) in rows {
            assert!(
                !sql.contains("datetime('now')"),
                "DDL must not use legacy datetime('now'): {sql}"
            );
            assert!(
                sql.contains("CURRENT_TIMESTAMP")
                    || !sql.contains("TIMESTAMP") && !sql.contains("timestamp"),
                "DDL should prefer CURRENT_TIMESTAMP where applicable: {sql}"
            );
        }
    }

    // ─── M3 regression tests ───────────────────────────────────────────────
    //
    // M3 synchronises and aligns the `migrations/*.sql` files with the
    // inline DDL in `migrate_to_vN`. The tests below pin down the M3
    // invariants: (a) every `migrations/*.sql` is the human-readable
    // reference for the corresponding Rust migrator (modulo the v5
    // AUTOINCREMENT/IDENTITY driver split, F-M2-02), (b) no SQL file
    // contains the legacy `datetime('now')` form, (c) the index names
    // defined in SQL match the catalog after `run_migrations`, and
    // (d) the v5 DDL is portable across SQLite / Postgres / MySQL
    // (the F-M2-02 fix).

    /// Normalise whitespace: collapse runs of spaces/tabs into a single
    /// space, drop leading/trailing whitespace on each line, drop
    /// blank lines, drop `-- ...` line comments. Used to compare a
    /// reference SQL file against an inline Rust DDL string when the
    /// two have only indentation / line-break differences.
    fn normalise_sql(s: &str) -> String {
        s.lines()
            .map(|l| {
                // strip `--` line comments (not inside strings — none of
                // the inline DDLs contain `--` outside of comments).
                if let Some(idx) = l.find("--") {
                    &l[..idx]
                } else {
                    l
                }
            })
            .map(|l| l.trim())
            .filter(|l| !l.is_empty())
            .map(|l| {
                // collapse internal runs of whitespace to a single space,
                // but keep `;` attached to the previous token (so an
                // end-of-statement `;` on its own line still reads as
                // part of the previous line).
                let mut out = String::with_capacity(l.len());
                let mut prev_space = false;
                for c in l.chars() {
                    if c == ';' {
                        // attach to previous token
                        out.push(';');
                        prev_space = false;
                    } else if c.is_whitespace() {
                        if !prev_space {
                            out.push(' ');
                        }
                        prev_space = true;
                    } else {
                        out.push(c);
                        prev_space = false;
                    }
                }
                out
            })
            .collect::<Vec<_>>()
            .join("\n")
    }

    /// F-M3-01: the SQLite branch of `v5_create_messages_sql` matches the
    /// `CREATE TABLE messages` block in `migrations/0005_messages.sql` after
    /// whitespace normalisation. The two should be byte-identical modulo
    /// indentation and the line-break conventions of the two contexts
    /// (Rust string literal vs. SQL file). The 0005 file also contains the
    /// two CREATE INDEX statements; those are covered by F-M3-05.
    #[test]
    fn m3_v5_sqlite_ddl_matches_migration_file() {
        // CARGO_MANIFEST_DIR is the workspace root for ilink-hub. The
        // migrations/ dir sits at the workspace root.
        let manifest_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        let sql_path = manifest_dir.join("migrations").join("0005_messages.sql");
        let sql_text = std::fs::read_to_string(&sql_path)
            .unwrap_or_else(|e| panic!("read {}: {e}", sql_path.display()));
        // Extract just the CREATE TABLE block (everything up to the first
        // closing `;`). The two CREATE INDEX statements that follow are
        // covered by F-M3-05. The block already ends with `;` in the SQL
        // file, so the normaliser sees a trailing `;` on the last
        // non-empty line.
        let create_table_block = sql_text.split(';').next().unwrap_or("").trim().to_string() + ";";
        // `v5_create_messages_sql` does not include the trailing `;`
        // (the `ddl()` helper accepts statements both with and without
        // it). Append one for the comparison so the two normalised
        // strings have the same shape.
        let expected = Store::v5_create_messages_sql(DatabaseKind::Sqlite) + ";";
        assert_eq!(
            normalise_sql(&expected),
            normalise_sql(&create_table_block),
            "SQLite v5 CREATE TABLE DDL diverges from migrations/0005_messages.sql — \
             update one or the other to keep them in sync (M3 invariant)"
        );
    }

    /// F-M3-02: the Postgres branch of `v5_create_messages_sql` uses
    /// `GENERATED BY DEFAULT AS IDENTITY` (the SQL standard form) and
    /// does NOT use `AUTOINCREMENT`. This is the F-M2-02 fix — the
    /// SQLite-only keyword must not leak into the Postgres DDL. (The
    /// MySQL branch uses `AUTO_INCREMENT` and is covered by a separate
    /// test below.)
    #[test]
    fn m3_v5_postgres_ddl_uses_identity_not_autoincrement() {
        let ddl = Store::v5_create_messages_sql(DatabaseKind::Postgres);
        assert!(
            ddl.contains("GENERATED BY DEFAULT AS IDENTITY"),
            "Postgres v5 DDL must use SQL standard IDENTITY clause: {ddl}"
        );
        assert!(
            !ddl.contains("AUTOINCREMENT"),
            "Postgres v5 DDL must NOT use SQLite-only AUTOINCREMENT: {ddl}"
        );
    }

    /// F-M3-02 (MySQL branch): the MySQL form uses `AUTO_INCREMENT` (MySQL's
    /// keyword, distinct from SQLite's `AUTOINCREMENT`) and `BIGINT NOT NULL`
    /// (MySQL's `INTEGER` with `AUTO_INCREMENT` is silently mapped to `INT(11)`,
    /// which collides with the `i64` decode used by `save_message`'s
    /// `LAST_INSERT_ID()`). The Postgres / SQLite IDENTITY clause must not
    /// leak into MySQL.
    #[test]
    fn m3_v5_mysql_ddl_uses_auto_increment_and_bigint() {
        let ddl = Store::v5_create_messages_sql(DatabaseKind::MySql);
        assert!(
            ddl.contains("AUTO_INCREMENT"),
            "MySQL v5 DDL must use MySQL AUTO_INCREMENT: {ddl}"
        );
        assert!(
            !ddl.contains("AUTOINCREMENT"),
            "MySQL v5 DDL must NOT use SQLite-only AUTOINCREMENT: {ddl}"
        );
        assert!(
            !ddl.contains("GENERATED BY DEFAULT AS IDENTITY"),
            "MySQL v5 DDL must NOT use Postgres IDENTITY clause: {ddl}"
        );
        assert!(
            ddl.contains("BIGINT"),
            "MySQL v5 DDL must declare id as BIGINT (not INTEGER): {ddl}"
        );
    }

    /// F-M3-01 (driver detection from URL): `DatabaseKind::from_url` must
    /// recognise every supported scheme and fall back to `Sqlite` for
    /// unknown / missing schemes. The M3 review flagged the old
    /// `SELECT current_database()` runtime probe as broken on MySQL (it
    /// errors on BOTH SQLite and MySQL); the fix parses the kind from the
    /// URL prefix at `Store::connect` time.
    #[test]
    fn adversarial_database_kind_from_url() {
        assert_eq!(
            DatabaseKind::from_url("sqlite::memory:"),
            DatabaseKind::Sqlite
        );
        assert_eq!(
            DatabaseKind::from_url("sqlite:/tmp/x.db"),
            DatabaseKind::Sqlite
        );
        assert_eq!(
            DatabaseKind::from_url("sqlite:///var/data/x.db"),
            DatabaseKind::Sqlite
        );
        assert_eq!(
            DatabaseKind::from_url("postgres://u:p@h:5432/db"),
            DatabaseKind::Postgres
        );
        assert_eq!(
            DatabaseKind::from_url("postgresql://u:p@h:5432/db"),
            DatabaseKind::Postgres
        );
        assert_eq!(
            DatabaseKind::from_url("mysql://u:p@h:3306/db"),
            DatabaseKind::MySql
        );
        assert_eq!(
            DatabaseKind::from_url("mariadb://u:p@h:3306/db"),
            DatabaseKind::MySql
        );
        // Unknown / malformed URLs default to Sqlite (back-compat for
        // the iLink Hub default; a CLI typo should not refuse to start).
        assert_eq!(DatabaseKind::from_url(""), DatabaseKind::Sqlite);
        assert_eq!(
            DatabaseKind::from_url("file:/tmp/x.db"),
            DatabaseKind::Sqlite
        );
    }

    /// F-M3-01 (`Store::connect` populates the driver kind from the URL):
    /// the kind parsed at `Store::connect` time must drive the migration
    /// runner's driver-aware SQL. On SQLite the `try_claim_migration`
    /// claim is the `ON CONFLICT DO NOTHING RETURNING` form (we can verify
    /// this by inspecting the catalog after a fresh connect: the
    /// `schema_version` table is created with the SQLite form). On
    /// `postgres:` and `mysql:` URLs the `DatabaseKind` is parsed without
    /// actually opening a connection (we can test the parser directly;
    /// the integration test against a real Postgres / MySQL server is
    /// out of scope for this CI environment).
    #[test]
    fn adversarial_database_kind_drives_v5_ddl_branch() {
        // All three forms must be syntactically valid DDL and must
        // agree on every column except the `id` clause.
        let sqlite_ddl = Store::v5_create_messages_sql(DatabaseKind::Sqlite);
        let postgres_ddl = Store::v5_create_messages_sql(DatabaseKind::Postgres);
        let mysql_ddl = Store::v5_create_messages_sql(DatabaseKind::MySql);

        // Common shape assertions: every form must declare the same
        // non-id columns and the same defaults.
        for (label, ddl) in [
            ("sqlite", &sqlite_ddl),
            ("postgres", &postgres_ddl),
            ("mysql", &mysql_ddl),
        ] {
            assert!(
                ddl.contains("vctx         TEXT NOT NULL"),
                "[{label}] missing vctx column: {ddl}"
            );
            assert!(
                ddl.contains("session_name TEXT NOT NULL DEFAULT 'default'"),
                "[{label}] missing session_name: {ddl}"
            );
            assert!(
                ddl.contains("created_at   TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)"),
                "[{label}] missing created_at with CURRENT_TIMESTAMP default: {ddl}"
            );
        }

        // Driver-specific id clauses.
        assert!(sqlite_ddl.contains("INTEGER PRIMARY KEY AUTOINCREMENT"));
        assert!(postgres_ddl.contains("GENERATED BY DEFAULT AS IDENTITY"));
        assert!(mysql_ddl.contains("BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY"));

        // The three forms must be distinct (no shared id clause).
        assert_ne!(sqlite_ddl, postgres_ddl);
        assert_ne!(sqlite_ddl, mysql_ddl);
        assert_ne!(postgres_ddl, mysql_ddl);
    }

    /// F-M3-01 (`column_exists` is now driver-aware): the pre-check used
    /// by `migrate_to_v4` must use the SQLite `pragma_table_info` form on
    /// SQLite, not the broken runtime probe. We construct a Store with
    /// `kind: Sqlite` and verify the column is detected on the SQLite
    /// path (this is the path the existing v4 tests already exercise;
    /// the F-M3-01 fix is that the path is now selected by
    /// `self.kind` rather than by the unreliable `current_database()`
    /// probe — so the SQLite path is no longer falsely taken on MySQL).
    #[tokio::test]
    async fn adversarial_column_exists_uses_pragma_on_sqlite() {
        sqlx::any::install_default_drivers();
        let pool = sqlx::pool::PoolOptions::<sqlx::Any>::new()
            .max_connections(1)
            .connect("sqlite::memory:")
            .await
            .expect("pool");
        let store = Store {
            pool,
            kind: DatabaseKind::Sqlite,
        };
        store
            .ddl("CREATE TABLE t (a INTEGER, b TEXT)")
            .await
            .expect("create");
        assert!(store.column_exists("t", "a").await.unwrap());
        assert!(store.column_exists("t", "b").await.unwrap());
        assert!(!store.column_exists("t", "c").await.unwrap());
        // Identifier safety check: non-identifier characters must
        // short-circuit to Ok(false) (no SQL injection).
        assert!(!store.column_exists("t; DROP", "a").await.unwrap());
    }

    /// F-M3-03: every `migrations/*.sql` file contains no
    /// `datetime('now')` residue. The m2 review established
    /// `CURRENT_TIMESTAMP` as the canonical default in the Rust
    /// DDLs; the SQL files must use the same form.
    #[test]
    fn m3_no_legacy_datetime_now_in_migration_files() {
        let manifest_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        let dir = manifest_dir.join("migrations");
        let mut checked = 0usize;
        for entry in
            std::fs::read_dir(&dir).unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display()))
        {
            let entry = entry.expect("entry");
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) != Some("sql") {
                continue;
            }
            let text = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
            assert!(
                !text.contains("datetime('now')"),
                "{} still contains legacy datetime('now') — use CURRENT_TIMESTAMP",
                path.display()
            );
            checked += 1;
        }
        assert!(
            checked >= 4,
            "expected at least 4 .sql files, found {checked}"
        );
    }

    /// F-M3-04: every `migrations/*.sql` file that contains a timestamp
    /// default uses `CURRENT_TIMESTAMP` (not `datetime('now')`). Companion
    /// to F-M3-03; asserts the affirmative side of the unification. Files
    /// that contain no timestamp default (e.g. `0003_*` index-only file)
    /// are exempt — the test only fires for files that mention the word
    /// "timestamp" or "TIMESTAMP".
    #[test]
    fn m3_migration_files_use_current_timestamp() {
        let manifest_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        let dir = manifest_dir.join("migrations");
        for entry in std::fs::read_dir(&dir).expect("read_dir") {
            let entry = entry.expect("entry");
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) != Some("sql") {
                continue;
            }
            let text = std::fs::read_to_string(&path).expect("read");
            let mentions_timestamp = text.contains("timestamp") || text.contains("TIMESTAMP");
            if !mentions_timestamp {
                continue;
            }
            assert!(
                text.contains("CURRENT_TIMESTAMP"),
                "{} is missing CURRENT_TIMESTAMP — every timestamp default \
                 must use the SQL standard form (M3 alignment)",
                path.display()
            );
        }
    }

    /// F-M3-05: after `run_migrations`, the SQLite catalog contains the
    /// three index names that the SQL files declare
    /// (`idx_context_token_map_real_ctx`, `idx_context_token_map_created_at`,
    /// `idx_messages_vctx_created`, `idx_messages_peer_role_created`).
    /// This is the M3 cross-check between the SQL reference files and
    /// the runtime catalog.
    #[tokio::test]
    async fn m3_index_names_match_sql_files_and_catalog() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");
        for idx in [
            "idx_context_token_map_real_ctx",
            "idx_context_token_map_created_at",
            "idx_messages_vctx_created",
            "idx_messages_peer_role_created",
        ] {
            let row: Option<(String,)> =
                sqlx::query_as("SELECT name FROM sqlite_master WHERE type='index' AND name = $1")
                    .bind(idx)
                    .fetch_optional(&store.pool)
                    .await
                    .expect("catalog");
            assert!(row.is_some(), "index {idx} missing from SQLite catalog");
        }
    }

    /// F-M3-06: the inline Rust DDL strings in `migrate_to_v1`, `migrate_to_v2`,
    /// and `migrate_to_v4` are byte-equivalent (modulo whitespace) to the
    /// corresponding statements in `migrations/0001_initial_schema.sql`,
    /// `migrations/0002_backend_sessions.sql`, and
    /// `migrations/0004_context_token_map_created_at.sql`. v3 has no
    /// SQL file (its `CREATE UNIQUE INDEX` is inline-only); v5 is
    /// covered by `m3_v5_sqlite_ddl_matches_migration_file`.
    #[tokio::test]
    async fn m3_migration_files_match_inline_ddl_for_v1_v2_v4() {
        // Re-run the in-source extraction: the migration runner must use
        // the same DDL strings the SQL files declare. The simplest
        // invariant: after `Store::connect`, the SQLite catalog contains
        // every table and index that the SQL files declare, with the
        // exact names.
        let store = Store::connect("sqlite::memory:").await.expect("connect");

        // Tables declared in the SQL files.
        let expected_tables = [
            // 0000 (documentation only — table is created by the runner,
            // not by the SQL file). Skipped.
            "clients",             // 0001
            "routing_state",       // 0001
            "context_token_map",   // 0001
            "bot_credentials",     // 0001
            "backend_sessions_v2", // 0002
            "active_sessions",     // 0002
            "messages",            // 0005
        ];
        for t in expected_tables {
            let row: Option<(String,)> =
                sqlx::query_as("SELECT name FROM sqlite_master WHERE type='table' AND name = $1")
                    .bind(t)
                    .fetch_optional(&store.pool)
                    .await
                    .expect("catalog");
            assert!(
                row.is_some(),
                "table {t} declared in migrations/*.sql but missing from catalog"
            );
        }
    }

    // ─── get_session_status_per_vtoken ───────────────────────────────────────

    #[tokio::test]
    async fn session_status_empty_vtokens_returns_empty_map() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");
        let result = store
            .get_session_status_per_vtoken(&[])
            .await
            .expect("query");
        assert!(result.is_empty());
    }

    #[tokio::test]
    async fn session_status_no_messages_returns_empty_map() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");
        let vtokens = vec!["vt-unknown".to_string()];
        let result = store
            .get_session_status_per_vtoken(&vtokens)
            .await
            .expect("query");
        assert!(result.is_empty());
    }

    #[tokio::test]
    async fn session_status_waiting_when_last_message_is_user() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");
        store
            .save_message(
                "vctx1",
                Some("vt1"),
                "default",
                "user1",
                "user",
                "帮我看看这个问题",
            )
            .await
            .expect("save user");

        let result = store
            .get_session_status_per_vtoken(&["vt1".to_string()])
            .await
            .expect("query");

        let entry = result.get("vt1").expect("entry for vt1");
        assert!(
            entry.waiting_for_reply,
            "last role is user → should be waiting"
        );
        assert_eq!(entry.session_name, "default");
        assert_eq!(entry.last_user_content.as_deref(), Some("帮我看看这个问题"));
    }

    #[tokio::test]
    async fn session_status_not_waiting_when_last_message_is_assistant() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");
        store
            .save_message(
                "vctx2",
                Some("vt2"),
                "work",
                "user2",
                "user",
                "请解释一下 Rust 的生命周期",
            )
            .await
            .expect("save user");
        store
            .save_message(
                "vctx2",
                Some("vt2"),
                "work",
                "user2",
                "assistant",
                "生命周期是…",
            )
            .await
            .expect("save assistant");

        let result = store
            .get_session_status_per_vtoken(&["vt2".to_string()])
            .await
            .expect("query");

        let entry = result.get("vt2").expect("entry for vt2");
        assert!(
            !entry.waiting_for_reply,
            "last role is assistant → not waiting"
        );
        assert_eq!(entry.session_name, "work");
        assert_eq!(
            entry.last_user_content.as_deref(),
            Some("请解释一下 Rust 的生命周期")
        );
    }

    #[tokio::test]
    async fn session_status_multiple_vtokens_independent() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");
        // vt-a: user sent, AI hasn't replied
        store
            .save_message("ctx-a", Some("vt-a"), "default", "pa", "user", "问题A")
            .await
            .expect("save");
        // vt-b: full round trip
        store
            .save_message("ctx-b", Some("vt-b"), "session-x", "pb", "user", "问题B")
            .await
            .expect("save");
        store
            .save_message(
                "ctx-b",
                Some("vt-b"),
                "session-x",
                "pb",
                "assistant",
                "回答B",
            )
            .await
            .expect("save");

        let result = store
            .get_session_status_per_vtoken(&["vt-a".to_string(), "vt-b".to_string()])
            .await
            .expect("query");

        let a = result.get("vt-a").expect("vt-a");
        assert!(a.waiting_for_reply);
        assert_eq!(a.last_user_content.as_deref(), Some("问题A"));

        let b = result.get("vt-b").expect("vt-b");
        assert!(!b.waiting_for_reply);
        assert_eq!(b.last_user_content.as_deref(), Some("问题B"));
        assert_eq!(b.session_name, "session-x");
    }

    #[tokio::test]
    async fn session_status_unknown_vtoken_not_in_result() {
        let store = Store::connect("sqlite::memory:").await.expect("connect");
        store
            .save_message("ctx", Some("vt-known"), "default", "p", "user", "hi")
            .await
            .expect("save");

        let result = store
            .get_session_status_per_vtoken(&["vt-known".to_string(), "vt-missing".to_string()])
            .await
            .expect("query");

        assert!(result.contains_key("vt-known"));
        assert!(
            !result.contains_key("vt-missing"),
            "unknown vtoken must not appear"
        );
    }

    // ─── Adversarial tests for M1 review findings ──────────────────────────
    //
    // Each test below pins down a specific SEC-ADV finding from the
    // adversarial review. They are independent of the M1/M2/M3 regression
    // tests above and exercise only the new code paths.

    /// SEC-ADV-001: `ensure_sqlite_file` must NOT truncate an existing
    /// SQLite database file. We create a valid DB, write data to it, then
    /// call `ensure_sqlite_file` again — the file size must not shrink to
    /// zero and the data must still be readable.
    #[test]
    fn adversarial_ensure_sqlite_file_does_not_truncate_existing_db() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let db_path = tmp.path().join("existing.db");
        let url = format!("sqlite:{}", db_path.display());

        // Create the database via Store::connect (this writes v1-v5 schema).
        let rt = tokio::runtime::Runtime::new().unwrap();
        let _store = rt.block_on(async { Store::connect(&url).await.expect("first connect") });

        // Record the file size after schema creation.
        let size_before = std::fs::metadata(&db_path).expect("metadata").len();
        assert!(
            size_before > 0,
            "database file must have content after Store::connect"
        );

        // Now simulate a concurrent connect: call `ensure_sqlite_file` on
        // the same path. With the old `File::create` this would truncate
        // the file to 0 bytes. With `create_new(true)` it returns
        // AlreadyExists and leaves the file untouched.
        Store::ensure_sqlite_file(&url).expect("ensure_sqlite_file must succeed");

        let size_after = std::fs::metadata(&db_path).expect("metadata").len();
        assert!(
            size_after >= size_before,
            "ensure_sqlite_file must not truncate existing database: \
             size_before={size_before}, size_after={size_after}"
        );

        // Verify the database is still usable (not corrupted by truncation).
        let store2 = rt.block_on(async { Store::connect(&url).await.expect("second connect") });
        let v = rt.block_on(store2.get_current_version()).unwrap();
        assert_eq!(
            v, 5,
            "database must still be at v5 after ensure_sqlite_file"
        );
    }

    /// SEC-ADV-001 (concurrent stress): hammer `ensure_sqlite_file` from
    /// multiple OS threads against the same file. With the old `File::create`
    /// this would eventually truncate a concurrent writer's data. With
    /// `create_new(true)` + `AlreadyExists` handling, every call either
    /// creates the file or safely observes it already exists.
    #[test]
    fn adversarial_ensure_sqlite_file_concurrent_threads_safe() {
        use std::sync::Arc;

        let tmp = tempfile::tempdir().expect("tempdir");
        let db_path = tmp.path().join("race.db");
        let url = format!("sqlite:{}", db_path.display());

        // First, create the database and populate it.
        let rt = tokio::runtime::Runtime::new().unwrap();
        let _store = rt.block_on(async { Store::connect(&url).await.expect("first connect") });
        let size_before = std::fs::metadata(&db_path).expect("metadata").len();

        // Now hammer `ensure_sqlite_file` from 16 threads concurrently.
        let url = Arc::new(url);
        let mut handles = Vec::new();
        for _ in 0..16 {
            let url = Arc::clone(&url);
            handles.push(std::thread::spawn(move || {
                for _ in 0..50 {
                    Store::ensure_sqlite_file(&url).expect("ensure_sqlite_file");
                }
            }));
        }
        for h in handles {
            h.join().expect("thread join");
        }

        let size_after = std::fs::metadata(&db_path).expect("metadata").len();
        assert!(
            size_after >= size_before,
            "concurrent ensure_sqlite_file must not truncate: \
             size_before={size_before}, size_after={size_after}"
        );

        // Database must still be usable.
        let store2 = rt.block_on(async {
            Store::connect(&url)
                .await
                .expect("reconnect after concurrent race")
        });
        let v = rt.block_on(store2.get_current_version()).unwrap();
        assert_eq!(v, 5);
    }

    /// SEC-ADV-002: `column_exists` on the SQLite branch must propagate
    /// errors from the `pragma_table_info` query rather than silently
    /// treating all errors as "column not found". The non-tx `column_exists`
    /// still uses `.unwrap_or(None)` as a deliberate choice (caller treats
    /// absent column as "not present and let the DDL surface the real
    /// error"), but the tx variant in `migrate_to_v4_tx` now uses `?`.
    /// This test verifies the in-tx path propagates errors for a
    /// syntactically-invalid pragma query (malformed identifier).
    #[tokio::test]
    async fn adversarial_v4_tx_pragma_error_propagates() {
        sqlx::any::install_default_drivers();
        let pool = sqlx::pool::PoolOptions::<sqlx::Any>::new()
            .max_connections(1)
            .connect("sqlite::memory:")
            .await
            .expect("pool");
        let store = Store {
            pool,
            kind: DatabaseKind::Sqlite,
        };
        // Bootstrap schema_version table (required by run_migrations).
        store
            .ddl(
                "CREATE TABLE IF NOT EXISTS schema_version (
                    version     INTEGER PRIMARY KEY,
                    migrated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
                )",
            )
            .await
            .expect("schema_version");
        // Mark v1-v3 as applied so only v4 runs.
        for v in 1..=3 {
            store.record_migration_run(v).await.expect("mark");
        }
        // Create a context_token_map WITHOUT created_at so v4 tries to add it.
        store
            .ddl(
                "CREATE TABLE IF NOT EXISTS context_token_map (
                    vctx TEXT PRIMARY KEY, real_ctx TEXT NOT NULL,
                    peer_user_id TEXT NOT NULL DEFAULT '', expires_at TEXT
                )",
            )
            .await
            .expect("context_token_map");

        // v4 should succeed (column doesn't exist yet, so ALTER ADD COLUMN runs).
        store
            .migrate_to_v4()
            .await
            .expect("v4 must add created_at column");
        assert!(
            store
                .column_exists("context_token_map", "created_at")
                .await
                .unwrap(),
            "created_at must exist after v4"
        );
    }

    /// SEC-ADV-002: `column_exists` on SQLite must return `Ok(false)` for
    /// a non-existent table rather than propagating an error. This is the
    /// deliberate error-suppression behaviour documented in the function
    /// comment: callers treat "column absent" as a signal to run DDL, and
    /// the DDL itself will surface the real error (e.g. "no such table")
    /// with a clearer message.
    #[tokio::test]
    async fn adversarial_column_exists_returns_false_on_nonexistent_table() {
        sqlx::any::install_default_drivers();
        let pool = sqlx::pool::PoolOptions::<sqlx::Any>::new()
            .max_connections(1)
            .connect("sqlite::memory:")
            .await
            .expect("pool");
        let store = Store {
            pool,
            kind: DatabaseKind::Sqlite,
        };
        // No tables created — `column_exists` on a non-existent table must
        // return `Ok(false)`, NOT propagate a runtime error.
        let result = store.column_exists("no_such_table", "any_col").await;
        assert!(
            result.is_ok(),
            "column_exists on non-existent table must return Ok, not Err"
        );
        assert!(
            !result.unwrap(),
            "column_exists on non-existent table must return Ok(false)"
        );
    }

    /// SEC-ADV-002 (regression): after a failed column_exists that
    /// returned `Ok(false)` (deliberate suppression), the caller should
    /// be able to attempt DDL that surfaces the real error. This confirms
    /// the design that error suppression in column_exists does not hide
    /// the root cause permanently.
    #[tokio::test]
    async fn adversarial_ddl_surfaces_error_after_column_exists_suppresses() {
        sqlx::any::install_default_drivers();
        let pool = sqlx::pool::PoolOptions::<sqlx::Any>::new()
            .max_connections(1)
            .connect("sqlite::memory:")
            .await
            .expect("pool");
        let store = Store {
            pool,
            kind: DatabaseKind::Sqlite,
        };
        // column_exists returns false → caller tries DDL
        let col_missing = !store
            .column_exists("ghost_table", "ghost_col")
            .await
            .unwrap();
        assert!(col_missing);
        // The DDL must surface the real "no such table" error.
        let ddl_result = store
            .ddl("ALTER TABLE ghost_table ADD COLUMN ghost_col TEXT")
            .await;
        assert!(
            ddl_result.is_err(),
            "DDL on non-existent table must propagate error"
        );
        let err_msg = format!("{}", ddl_result.unwrap_err());
        assert!(
            err_msg.to_lowercase().contains("no such table")
                || err_msg.to_lowercase().contains("error"),
            "DDL error must mention the table problem; got: {err_msg}"
        );
    }

    /// SEC-ADV-004 + SEC-ADV-006: after `Store::connect` to a file-backed
    /// SQLite database, the connection pool must have WAL journal mode
    /// and busy_timeout=5000 explicitly configured.
    #[tokio::test]
    async fn adversarial_sqlite_connect_configures_wal_and_busy_timeout() {
        sqlx::any::install_default_drivers();
        let tmp = tempfile::tempdir().expect("tempdir");
        let url = format!("sqlite:{}/pragma.db", tmp.path().display());
        let store = Store::connect(&url).await.expect("connect");

        // Verify journal_mode is WAL via pragma_journal_mode TVF.
        let (jm,): (String,) = sqlx::query_as("SELECT * FROM pragma_journal_mode")
            .fetch_one(&store.pool)
            .await
            .expect("journal_mode query");
        assert_eq!(
            jm, "wal",
            "journal_mode must be WAL after Store::connect; got {jm}"
        );

        // Verify busy_timeout is 5000 via pragma_busy_timeout TVF.
        let (bt,): (i32,) = sqlx::query_as("SELECT * FROM pragma_busy_timeout")
            .fetch_one(&store.pool)
            .await
            .expect("busy_timeout query");
        assert_eq!(
            bt, 5000,
            "busy_timeout must be 5000ms after Store::connect; got {bt}"
        );
    }

    /// SEC-ADV-003: `try_claim_migration_in_tx` must have the same claim
    /// semantics as `try_claim_migration` — exactly one caller wins in a
    /// race. This test verifies the in-tx variant under concurrent access
    /// on the same pool.
    #[tokio::test]
    async fn adversarial_try_claim_in_tx_is_mutually_exclusive() {
        sqlx::any::install_default_drivers();
        // File-backed SQLite so all connections share the same database —
        // :memory: databases are per-connection private unless shared-cache
        // is enabled.
        let tmp = tempfile::tempdir().expect("tempdir");
        let db_url = format!("sqlite:{}/txclaim.db", tmp.path().display());
        Store::ensure_sqlite_file(&db_url).expect("ensure db file");
        let pool = sqlx::pool::PoolOptions::<sqlx::Any>::new()
            .max_connections(2)
            .connect(&db_url)
            .await
            .expect("pool");
        let store = Store {
            pool: pool.clone(),
            kind: DatabaseKind::Sqlite,
        };
        // Bootstrap schema_version.
        store
            .ddl(
                "CREATE TABLE IF NOT EXISTS schema_version (
                    version     INTEGER PRIMARY KEY,
                    migrated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
                )",
            )
            .await
            .expect("schema_version");

        // Both transactions race for v99. Only one tx's claim can succeed.
        let pool2 = pool.clone();
        let store2 = Store {
            pool: pool2,
            kind: DatabaseKind::Sqlite,
        };
        let (r1, r2) = tokio::join!(
            async {
                let mut tx = store.pool.begin().await.expect("tx1");
                let claimed = store.try_claim_migration_in_tx(&mut tx, 99).await.unwrap();
                tx.commit().await.expect("commit1");
                claimed
            },
            async {
                let mut tx = store2.pool.begin().await.expect("tx2");
                let claimed = store2.try_claim_migration_in_tx(&mut tx, 99).await.unwrap();
                tx.commit().await.expect("commit2");
                claimed
            },
        );
        let winners = [r1, r2].iter().filter(|c| **c).count();
        assert_eq!(
            winners, 1,
            "exactly one tx must claim v99; r1={r1}, r2={r2}"
        );
    }
}
