-- Chat message history table for per-session conversation context.
-- Stores both user messages (role='user') and assistant replies (role='assistant').
-- Indexed for efficient per-conversation and per-peer queries.
--
-- Note on the `id` column: this file documents the SQLite form. The Rust
-- migrator (`Store::migrate_to_v5` in src/store/mod.rs) selects the
-- per-driver DDL at runtime so the table is portable across SQLite, Postgres,
-- and MySQL — `AUTOINCREMENT` is a SQLite-only keyword, so on Postgres /
-- MySQL the migrator substitutes the SQL standard
-- `GENERATED BY DEFAULT AS IDENTITY` (Postgres 10+, MySQL 8.0+). Both forms
-- produce an auto-incrementing BIGINT-equivalent primary key. See F-M2-02
-- in the m2 review-findings.yaml for the rationale.

CREATE TABLE IF NOT EXISTS messages (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    vctx         TEXT NOT NULL,
    vtoken       TEXT,
    session_name TEXT NOT NULL DEFAULT 'default',
    peer_user_id TEXT NOT NULL DEFAULT '',
    role         TEXT NOT NULL,
    content      TEXT NOT NULL,
    created_at   TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE INDEX IF NOT EXISTS idx_messages_vctx_created
    ON messages (vctx, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_messages_peer_role_created
    ON messages (peer_user_id, role, created_at DESC);
